import type { Metadata } from "next";
import { Geist, Archivo_Black, Audiowide } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/nav-menu/NavMenu";
import { ThemeProvider } from "@/components/ui/theme-provider";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const archivoBlack = Archivo_Black({
  weight: "400",
  variable: "--font-archivo-black",
  subsets: ["latin"],
});
export const audiowide = Audiowide({
  weight: "400",
  variable: "--font-audio",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Nextjs auth app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={` ${geistSans.className} ${audiowide.variable} ${archivoBlack.variable} h-full antialiased`}
    >
      <body className="flex min-h-dvh flex-col">
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <NavMenu />
          </header>
          <main className="flex-1">{children}</main>
          <footer>footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
